%%{init: {"gitGraph": {"rotateCommitLabel": false}} }%%
gitGraph
    commit id: "a1"
    commit id: "b2"
    branch feature
    checkout feature
    commit id: "c3"
    checkout main
    commit id: "e5"
    merge feature id: "m6 (2 parents)"
